# Generated by Django 4.2.6 on 2023-11-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='college_management_app.courses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_management_app.sessionyearmodel'),
        ),
    ]
