# Generated by Django 4.2.6 on 2023-11-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0003_alter_staffs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
