# Generated by Django 4.2.7 on 2023-11-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0009_alter_courses_id_alter_sessionyearmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
