# Generated by Django 4.2.7 on 2023-11-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0011_alter_students_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college_management_app.students'),
        ),
    ]
